### ISSUE TITLE
Adjust structure of multilingual descriptions to align with other API attributes

### ISSUE THREAD

**Issue by dshorthouse** [AAFC-BICoE/object-store-api#302]
In other modules, there is a `multilingualDescription` with a `descriptions` key whose value is an array like:
```
[{lang: "en", desc: nil}, {lang: "fr", desc: nil}]
```
Here, the language code is a key either `en` or `fr`. Can we align all these to be the same structure?

**Comment by cgendreau** [comment]
on managed-attribute ?

**Comment by cgendreau** [comment]
And newer managed-attributes (collection) don't have multilingual description so I think `descriptions` here should be removed.

**Comment by dshorthouse** [comment]
Yeah, I figured these were in flux. Agree that `descriptions` should be removed here and in collection managed attributes...unless the intent here was use them for tooltips.

**Comment by cgendreau** [comment]
actually they are in the ui in object-store so I guess the real question is do we want them or not. If the answer is yes they should be available on both (object-store and collection) and use `multilingualDescription`.

**Comment by dshorthouse** [comment]
In that case, I vote we keep them (best not cause a regression) AND use `multilingualDescription` so that we please our international partners.

**Comment by dshorthouse** [comment]
I see that the key for these is now `multilingual_description` whereas that in Collecting Method & elsewhere is `multilingualDescription`. Can we make all these `multilingualDescription'?

**Comment by cgendreau** [comment]
not sure, the same code is used in both places.
